
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sumup_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'sumup_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  sumup_analytics:
    # Config for staging models
    staging:
      +docs:
        node_color: "blue"
      +materialized: view
    
    # Config for intermediate models
    intermediate:
      +docs:
        node_color: "green"
      +materialized: view

    # Config for marts models (tables for BI/reporting)
    marts:
      +docs:
        node_color: "orange"
      +materialized: table
      +schema: marts
    
    # Config for analysis queries (Tables for BI performance)
    analysis:
      +docs:
        node_color: "red"
      +materialized: table
      +schema: analysis
